extends Node

signal monster_selected(monster)
signal monster_selected_updated()
signal location_selected()
signal direction_selected()
signal monster_summoned(monster)
signal monster_summoned_canceled()
signal monster_summoned_failed()
signal state_changed(state)
signal puzzle_set()
signal puzzle_solved()
signal incantation_typing()
signal incantation_stopped_typing()
signal incantation_typing_updated()
signal summoning_animation_finished()
